///! Creates the object file with ABI compatible with kernel 2.2.5
// Autogenerated file for Project225

const std = @import("std");

pub fn build(b: *std.Build) void {
    // These options are required to generate an ABI compatible.
    const target = b.resolveTargetQuery(.{
        .cpu_arch = .x86,
        .os_tag = .freestanding,
        .abi = .none,
    });
    const optimize = .ReleaseSmall;

    // Root module. This is our "main zig"
    const root_mod = b.createModule(.{
        .root_source_file = b.path("version.zig"),
        .target = target,
        .optimize = optimize,
    });
    // Common general-purpose modules
    // --- BEGIN common modules
    const common_mod = b.createModule(.{
        .root_source_file = b.path("../_common_modules/common.zig"),
        .target = target,
        .optimize = optimize,
    });
    // This allow use the module without extension, like system ones.
    root_mod.addImport("common", common_mod);
    // --- END common modules

    const obj = b.addObject(.{
        .name = "version",
        .root_module = root_mod,
    });

    // Copy output
    //const out_path = "version.o";    

    // Default output to zig-out/. Another path can be forced
    // with zig build --prefix path
    const install_file = b.addInstallFile(
        obj.getEmittedBin(),
        "version.o",
    );

    const build_step = b.step("build", "Build object");
    build_step.dependOn(&install_file.step);
    b.default_step = build_step;
}
